### ISSUE TITLE
How to use Bubble Chart using geom-point package?

### ISSUE THREAD

**Issue by ibrahimrehman1** [graphiquejs/graphique#22]
Following is the code which I have implemented till now but I don't know how to add bubble chart:

```
   <GG
      data={stocks.filter((d) => d.symbol === 'AAPL')}
      aes={{
        x: (d) => new Date(d.date),
        y: (d) => d.marketCap,
      }}
    >
      <GeomPoint/>
    </GG>
```

**Comment by madams1** [comment]
hi @ibrahimrehman1 — you should be able to create a bubble chart by including a `size` aesthetic mapped to a numeric value.

A timeseries chart is probably not the best example for a bubble chart, but with the `penguins` dataset, you should be able to create a bubble chart with something like:

```tsx
import { GG } from "@graphique/graphique";
import { GeomPoint } from "@graphique/geom-point";
import { penguins, Penguin } from "@graphique/datasets";

<GG
  data={penguins}
  aes={{
    x: (d: Penguin) => d.beakLength,
    y: (d: Penguin) => d.flipperLength,
    fill: (d: Penguin) => d.species,
    stroke: (d: Penguin) => d.species,
    size: (d: Penguin) => d.bodyMass,
  }}
>
  <GeomPoint fillOpacity={0.1} strokeOpacity={0.5} />
</GG>
```
<img width="492" alt="image" src="https://user-images.githubusercontent.com/2267966/191866764-7237f4c8-a6fe-45dc-b32b-814cf8f68bdd.png">

**Comment by ibrahimrehman1** [comment]
> hi @ibrahimrehman1 — you should be able to create a bubble chart by including a `size` aesthetic mapped to a numeric value.
> 
> A timeseries chart is probably not the best example for a bubble chart, but with the `penguins` dataset, you should be able to create a bubble chart with something like:
> 
> ```tsx
> import { GG } from "@graphique/graphique";
> import { GeomPoint } from "@graphique/geom-point";
> import { penguins, Penguin } from "@graphique/datasets";
> 
> <GG
>   data={penguins}
>   aes={{
>     x: (d: Penguin) => d.beakLength,
>     y: (d: Penguin) => d.flipperLength,
>     fill: (d: Penguin) => d.species,
>     stroke: (d: Penguin) => d.species,
>     size: (d: Penguin) => d.bodyMass,
>   }}
> >
>   <GeomPoint fillOpacity={0.1} strokeOpacity={0.5} />
> </GG>
> ```
> <img width="492" alt="image" src="https://user-images.githubusercontent.com/2267966/191866764-7237f4c8-a6fe-45dc-b32b-814cf8f68bdd.png">
> 

Great thank you 👍
