### ISSUE TITLE
full support for React 18

### ISSUE THREAD

**Issue by madams1** [graphiquejs/graphique#7]
When used with React 18, no geometry elements are displayed initially — they're stuck in their "starting" positions/appearances (e.g. horizontal lines with near-zero opacity — see below).

```tsx
<GG
  data={stocks}
  aes={{
    x: (d: Stock) => new Date(d.date),
    y: (d: Stock) => d.marketCap,
    stroke: (d: Stock) => d.symbol,
  }}
  isContainerWidth
  margin={{ left: 50 }}
>
  <GeomLine />
</GG>
```

<img width="944" alt="image" src="https://user-images.githubusercontent.com/2267966/162048976-1dbe03dc-9366-44d0-87a5-2fa77fcf538b.png">

This is likely due to how React 18 is now handling the rendering/updates/transitions specified by react-move (e.g. [here](https://github.com/graphiquejs/graphique/blob/main/packages/geom-line/src/geomLine.tsx#L153-L162) and [here](https://github.com/graphiquejs/graphique/blob/main/packages/geom-line/src/geomLine.tsx#L209-L212)).

Also see [a related animation/transition bug](https://github.com/pmndrs/react-spring/issues/1828) for react-spring.

A workaround is to ensure strict mode is disabled — do not use `<StrictMode>` in your app (in a Next.js app, set `reactStrictMode: false` in `next.config.js`). This at least draws the geometries, but mouseovers / tooltips still seem to not be working at all.

**Comment by joshuaellis** [comment]
I've launched a beta for `react18` that should resolve issues and be good to go – `9.4.5-beta.1` please feel free to give it a go and any issue feedback on that issue you linked too :)

**Comment by madams1** [comment]
closing this since it's resolved by not using strict mode, react 19 is stable, and eventual plans for moving to react-spring
